### ISSUE TITLE
Notifications: Signals for me

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/lifemaker#10]
Once in a day, the server will do matching of signals created in last 24 hours, with users based on interests. Then server will send a notification to users with count of smoke signals.
'{count} new Smoke Signals for you. {totalCount} new Smoke Signals in all'

**Comment by vaibhavmule** [comment]
Hi @silv3r and @awesomepankaj,

Please have a look how f8app solved Android push notification.

Here is a link https://productpains.com/post/react-native/push-notifications-on-android

**Comment by mastersilv3r** [comment]
Thanks Vaibhav. Shall check this :)
