### ISSUE TITLE
Main content on home page

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/lifemaker#58]
LifeMaker is a completely community owned, open source (link to github  here) and self-sustaining platform built to help us make our lives meaningfully better. It is backed by technology to enable:

Evaluation and evolution of our lives based on feedback from our environment
Skill, interest or location based connection and action
Resource mobilization to support meaningful projects and valued members.

Our Android application is on the Play Store (link here). It has limited features today and under active development. We invite those who want to join today itself, test and give suggestions. We are also planning to launch a webapp in next few months.

**Comment by mastersilv3r** [comment]
point one needs to be changed.
Evaluation and evolution of our lives and projects based on feedback from our environment

**Comment by vaibhavmule** [comment]
@mastersilv3r 

Now, I'm liking a homepage with minimal content that gives better information about LifeMaker.

**Comment by mastersilv3r** [comment]
the karma is still there though. we need to remove it.

**Comment by vaibhavmule** [comment]
@mastersilv3r  Done!
