### ISSUE TITLE
Create mockups for following pages

### ISSUE THREAD

**Issue by abhishekbose87** [Mindgreppers/lifemaker#76]
https://drive.google.com/file/d/0B_TXWehSVFOPNVFWSFNGRUVoN2c/view?usp=sharing
- [ ] #67 Activity Page(For home page and user's activities both)
- [ ] #68 User page
- [ ] #71 User settings
- [ ] #72 New request
- [ ] #73 New offer
- [ ] #74 New experience
- [ ] #75 Registration page 
- [ ] Offer page
- [ ] Experience page
- [ ] Request page
- [ ] Notifications view
- [ ] Boarding screens
- [ ] Messages

**Comment by Shan009** [comment]
Includes all the mockups

https://moqups.com/shanah009/NDfGppok
