### ISSUE TITLE
UI preview after preliminary discussions

### ISSUE THREAD

**Issue by bharatagarwal** [Mindgreppers/lifemaker#84]
Jashan and I have made attempted to fit in the mockups made by @Shan009 into the material ui guidelines, while also attempting to give a theme to the application.

While I chose to go with dawn, in keeping with the idea of awakening, Jashan has chosen a more grounded tone, hinting at the use of natural materials in the exchanges - wood, sky.

Opinions sought on logos, icons (for thanks/no thanks, smoke signal). 

<img src="https://cloud.githubusercontent.com/assets/15229351/14635458/0fcb80f4-0644-11e6-85d8-be693b34cc49.jpg" width="360">
<img src="https://cloud.githubusercontent.com/assets/15229351/14635414/e46f5156-0643-11e6-94b7-f95adff9e931.jpg" width="360">
<img src="https://cloud.githubusercontent.com/assets/15229351/14635415/e472890c-0643-11e6-8d1c-6584ac5388d9.jpg" width="360">

![1](https://cloud.githubusercontent.com/assets/15229351/14635470/18f961a0-0644-11e6-8c7c-c063ca2aa204.jpg)
![2](https://cloud.githubusercontent.com/assets/15229351/14635477/1bf25d26-0644-11e6-872e-7cb0368c7300.jpg)
![3](https://cloud.githubusercontent.com/assets/15229351/14635475/1bef25de-0644-11e6-9901-d590caa95b6b.jpg)
![4](https://cloud.githubusercontent.com/assets/15229351/14635476/1bf17550-0644-11e6-81ba-097b412a8537.jpg)
![5](https://cloud.githubusercontent.com/assets/15229351/14635474/1beecbb6-0644-11e6-8625-7a488d6f30d1.jpg)

**Comment by bharatagarwal** [comment]
Uploading the latest iteration of the UI, with inputs from federico and @mastersilv3r. Included are mockups of the smoke signal creation process, also introducing the purushottam inspired concepts of dharma, kama, vidya and artha.

[LifeMaker UI-4.pdf](https://github.com/Mindgreppers/lifemaker/files/229977/LifeMaker.UI-4.pdf)

**Comment by Shan009** [comment]
[LifeMaker UI copy 2.pdf](https://github.com/Mindgreppers/lifemaker/files/242178/LifeMaker.UI.copy.2.pdf)
