### ISSUE TITLE
Navigating between different screens in the app

### ISSUE THREAD

**Issue by abhishekbose87** [Mindgreppers/lifemaker#85]
Here are some links which suggest that `NavigationExperimental` is the component that will be used for navigating between screens instead of `Navigator`
- https://github.com/ericvicenti/navigation-rfc/blob/master/Docs/NavigationOverview.md

Also there are some examples at - https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/NavigationExperimental

@mastersilv3r @awesomepankaj Should we go ahead and used NavigationExperimental then ?

**Comment by mastersilv3r** [comment]
If it is the recommended way then sure go ahead.
