### ISSUE TITLE
LifeMaker@HillHacks2016

### ISSUE THREAD

**Issue by fedeniko** [Mindgreppers/lifemaker#98]
[https://lifemakersite.wordpress.com/howtoplay/]

**Comment by mastersilv3r** [comment]
Let us meet at 10:30 to discuss next steps for tomorrow and release?

**Comment by mastersilv3r** [comment]
Updated the playstore, latest apk is in place. Made minor fixes in text content. 
https://play.google.com/store/apps/details?id=com.lifemaker
